### ISSUE TITLE
Q1_Pro_V4.4.24.zip NOT FOUND

### ISSUE THREAD

**Issue by basilottac** [QIDITECH/QIDI_Q1_Pro#115]
Hello,
i try to update online my new QIDI Q1 Pro, but didnt work.
I try to retrive last firmware with  Github, but this link dont work:

https://github.com/QIDITECH/QIDI_Q1_Pro/releases/download/Q1_Pro_V4.4.24/Q1_Pro_V4.4.24.zip

i updated to version V4.4.21
Thank you,
CB.

**Comment by QIDITECH** [comment]
你可以通过以下连接找到文件
https://github.com/QIDITECH/QIDI_Q1_Pro/releases
https://github.com/QIDITECH/QIDI_Q1_Pro/releases/download/Q1_Pro_V4.4.24/Q1_V4.4.24.zip
