### ISSUE TITLE
[BUG] Stopping after starting the job won't work

### ISSUE THREAD

**Issue by Pheggas** [QIDITECH/QIDI_Q1_Pro#29]
Hey. A few days ago I received my Q1 Pro. I have firmware V4.4.16 and noticed when I started a print job and wanted to stop it a few seconds after, it would just say "Stop processing, please wait..." and the job would continue with all the macros before actual printing.
![IMG_20240524_125018172](https://github.com/QIDITECH/QIDI_Q1_Pro/assets/9994511/0f312dc4-30cf-419c-ab18-643166bebd48)

**Comment by CChen616** [comment]
This issue should have been fixed in version 4.4.19. Please try updating to the latest version to see if the problem is resolved.

**Comment by Pheggas** [comment]
Right. I was reading notes to each version but didn't know this bug is related to that fix. Thank you and I will update the firmware. If the issue wouldn't be present anymore in the latest firmware, I will close this issue with comment.

You can ignore this issue for now.
