### ISSUE TITLE
Head crashes at the end using Timelaps with Parkposition. Printposition is shifted afterwards.

### ISSUE THREAD

**Issue by MarkusKress** [QIDITECH/QIDI_Q1_Pro#47]
If you using the Timelaps with Parkposition, the head ramming over the end position. The printing can't continue, because the position of the head is shifted afterwards. The printer belt can be damaged.

**Comment by CChen616** [comment]
For the Q1 model, there are some non-printable areas. 

![image](https://github.com/QIDITECH/QIDI_Q1_Pro/assets/88018764/12387b5c-39e4-4aa9-948b-f64f5af26520)

When setting the parking position, try to avoid including the back end of the heated bed.

We will include extra instructions in the wiki and after-sales support.

For information on how to adjust the belts, please contact customer support or refer to the wiki.
