### ISSUE TITLE
Pre-print sequence doesn't equal up Z-heights of each Z motor rod anymore

### ISSUE THREAD

**Issue by Pheggas** [QIDITECH/QIDI_Q1_Pro#56]
Hello. Title might sound a bit strange but when the printer came home on v4.4.16 firmware, it has some kind of measurement for height difference between each Z-axis rod just before printing the file. It probed height of right rod first and then moved to left rod, made another measurement and then it equaled up those differences so the buildplate was perfectly straight between left and right rod.

It doesn't do this procedure anymore in v4.4.19 and i can see the buildplate compensation has to compensate a lot from one side to another in order to print properly. I even noticed issues of buildplate being too low (so even it compensates a lot, it's not perfect for this kind of big differences) and so filament didn't want to stick to buildplate on one side. Please re-add this feature in further versions.

![image](https://github.com/QIDITECH/QIDI_Q1_Pro/assets/9994511/a78a7816-af84-4599-84a6-d10f7b2e0d11)

You can see from the picture that on the left side, filament is squished perfectly. On the right side it's not squished enough causing it to detach from buildplate really easily.

**Comment by CChen616** [comment]
Even if the old leveling method ensures that the PEI plate is level, the adjustment screws might cause the platform to be at an angle with the axis. If this angle is too large, it could hinder the platform's movement.

![image](https://github.com/QIDITECH/QIDI_Q1_Pro/assets/88018764/55e207dc-5b06-4ac5-9a2a-14985eb79dda)

In the new version, by clicking `Platform Calibration` on the calibration page, the platform will first move downwards to zero position and then proceed with screw adjustments. This aims to ensure both the PEI plate is level and the platform is perpendicular to the axis.

**Comment by Pheggas** [comment]
That makes sense. I re-ran the calibration and it was horrible to see the difference between sides were like 1 cm. Thank you so much for detailed explanation even with image for better understanding. Now i know i should run platform calibration occasionally or after some disaster like power outage. Closing this issue.
