### ISSUE TITLE
Regarding Chamber Lights V4.4.21

### ISSUE THREAD

**Issue by m00x-pixel** [QIDITECH/QIDI_Q1_Pro#68]
1.)
With current Firmware V4.4.21 -> "Chamber light remains on in sleep mode" 

Is it possible to make it switchable, maybe directly from the config file?
I like it to be off in standby or sleepmode but maybe the option is switchable if needed.

2.)
Since i have the Printer, the light are slightly strong flickering only during printing but not during heating the Hotend/Bed.
I read about many posts on facebook many have this behavior.

Maybe there is some option to lower or set higher PWM frequency on the light output via config file?

Thanks for reading.

**Comment by dewi-ny-je** [comment]
The flickering is caused by the voltage on the power supply which is affected by the current draw of the bed. It can't be solved in software.

**Comment by CChen616** [comment]
Try add this to `[heater_bed]` section of the `printer.cfg`:
```
pwm_cycle_time: 0.0100
```

This can increase the frequency of the heated bed, stabilizing the voltage of the lights at a lower level. The default value is 0.1.

**Comment by dewi-ny-je** [comment]
Good idea

**Comment by m00x-pixel** [comment]
@CChen616 
Thank you for your response. 

The option pwm_cycle_time did the job, the flickering is much more less with it.

About the light sleep mode, what setting i need to set in order to turn off the light when the display goes to sleep or just set a time when the printer is in idle to turn off the light?

Thank you in advance.

**Comment by CChen616** [comment]
The lights now have a standalone switch, which can be found on the home page or in the "More Options" section in printing page.

**Comment by m00x-pixel** [comment]
Thank you for the response.

Maybe there is missunderstanding. I know you can manually turn off the light, but it is not the goal here. 

I just want to have back the automatic turn off when the  printer is in idle state and the display turn off.

**Comment by CChen616** [comment]
The main reason for having the lights not follow the screen-off is to accommodate timelapse. Keeping the lights on during long a printing ensures better quality for the final video.

I'm considering adding a configuration section to `klipper.cfg` to toggle whether the lights follow the screen sleep mode.

If works well, it will be added in next version.

**Comment by m00x-pixel** [comment]
I get it, Thank you.

So i think the issue could be closed.

**Comment by Tyler-DurdenRUL1** [comment]
hello @CChen616, quick question...
      my led strip in both my q1 pro's are flickering bad as well. I am currently in my printer.cfg section on fluidd and I am not sure if I type in that command directly in the heater_bed section on the last available line in that section? or do I need to add it somewhere else? I am just starting to get the hang of these commands for klipper. thank you
