### ISSUE TITLE
Save "don't show again"

### ISSUE THREAD

**Issue by samster395** [QIDITECH/QIDI_Q1_Pro#79]
Can this "don't prompt again" button be saved over a reboot 

Every time the printer reboots I have to press it again.

![20240828_211048](https://github.com/user-attachments/assets/46f664dc-ab07-4712-aaf7-132ac334e4ce)

**Comment by QIDITECH** [comment]
The prompt will be reset after the printer restarts. This is important for novice users, who often ignore the prompt and then set the wrong parameters or materials, causing the print to fail.
