### ISSUE TITLE
Q1 find online V4.4.24 but is not available here in Github

### ISSUE THREAD

**Issue by TinkerBarn** [QIDITECH/QIDI_Q1_Pro#80]
My Q1 Pro find in the printers menu for online updating a new version 4.4.24. The printer is configured to use aws as server. The actual installed firmware is V4.4.21

Where I can find the code and release notes regarding the V4.4.24 firmware and also regarding the never published V4.4.22 and V4.4.23?

Thank you.

**Comment by Rizadium** [comment]
https://github.com/QIDITECH/QIDI_Q1_Pro/releases

**Comment by TinkerBarn** [comment]
Release notes now online.
