### ISSUE TITLE
4.4.24 shows up as 4.4.23 when installed on Q1 Pro via offline update

### ISSUE THREAD

**Issue by Rizadium** [QIDITECH/QIDI_Q1_Pro#84]
Installed offline update via usb from https://github.com/QIDITECH/QIDI_Q1_Pro/releases/download/Q1_Pro_V4.4.24/Q1_V4.4.24.zip
Q1 Pro shows 4.4.23 was installed instead of 4.4.24.
If i do online check after the update, it will show there is an update to 4.4.24
![IMG_2826](https://github.com/user-attachments/assets/9130be4c-1150-46ef-99c4-c7ed05a86faf)
![IMG_2827](https://github.com/user-attachments/assets/c6ce7cc0-e185-4a5a-be5e-7ffa88996fcf)

**Comment by RCsForVetsPREZ** [comment]
same for me. now it dont want to connect via wifi to orcaslicer......

**Comment by QIDITECH** [comment]
Only the version number has a problem, does not affect other use, you can choose not to update to 4.4.24.
We have repaired and replaced the offline installation package.

**Comment by Rizadium** [comment]
Thank you
