### ISSUE TITLE
Camera dissapears after a printer restart in fluidd webinterface and in the android app

### ISSUE THREAD

**Issue by illuminati05** [QIDITECH/QIDI_Q1_Pro#86]
Printer: Qidi Q1 Pro
Firmware: 4.4.21 & 4.4.24

**Problem:** The webcam in fluidd does not work after a printer shutdown and start and the camera settings are defect.

Main GUI View after printer bottup:

![2024-09-15 16_09_53-QidiQ1ProNr1 _ Dashboard – Opera](https://github.com/user-attachments/assets/ddbb2c94-2d2f-4e64-8555-5537f7652acd)

Camera settings corrupt:

![2024-09-15 16_10_11-QidiQ1ProNr1 _ Settings – Opera](https://github.com/user-attachments/assets/eab4d39c-3d0c-41b5-b961-3e1149420c2a)

![2024-09-15 16_10_23-QidiQ1ProNr1 _ Settings – Opera](https://github.com/user-attachments/assets/a5a7b616-0ebc-4af3-bc96-3c60e0be4c91)

**Steps to fix:**

1.Enable the camera again:

![2024-09-15 16_10_23-QidiQ1ProNr1 _ Settings – Opera](https://github.com/user-attachments/assets/26fa7197-aa48-498a-af7d-414bfc11a986)

You can also delete the camera and add a new one with the same paramters !!!

2.Settings are ok after closing the dialog

![2024-09-15 16_10_38-QidiQ1ProNr1 _ Settings – Opera](https://github.com/user-attachments/assets/6934e281-d1e8-43e9-a34e-9b36ffe16fb3)

3.Camera works again in Main WebGUI

![2024-09-15 16_10_45-QidiQ1ProNr1 _ Dashboard – Opera](https://github.com/user-attachments/assets/bec0b9d8-dfcb-4682-9be8-2846248eb771)

**Attached files (LOGs)**

[Logs.zip](https://github.com/user-attachments/files/17006098/Logs.zip)

**Comment by illuminati05** [comment]
Printer is 2 weeks old and all stock

**Comment by illuminati05** [comment]
A new restart![Screenshot_20240917-175043.png](https://github.com/user-attachments/assets/897c52de-225d-4bd0-8f59-e08cefd9e993)

**Comment by QIDITECH** [comment]
There is no problem with the setting of the camera. I think it is caused by the lack of network data in the transmission process.
We will try to replicate and resolve the problem.

**Comment by illuminati05** [comment]
Do you need additional log files?

**Comment by kvdCode** [comment]
Hello, same problem here !

**Comment by QIDITECH** [comment]
We have identified the problem, through the background modification can solve part of the problem, but if you want to completely solve the problem, please wait for the next version of APP and software.

**Comment by illuminati05** [comment]
Is it possible to recieve a pre update to test the fix on my printer and if not how long does it take to get a new software version?

**Comment by QIDITECH** [comment]
QIDI Link expects to release a new version within two weeks.

**Comment by illuminati05** [comment]
Dear guys. How is the progress for the next release to fix this bug

**Comment by QIDITECH** [comment]
The new version of the APP has been submitted to the major app stores for approval and can be used after approval.
