### ISSUE TITLE
If printer is powered off while cleaning filament, it bends cleaner arm.

### ISSUE THREAD

**Issue by EsQueue81** [QIDITECH/QIDI_Q1_Pro#87]
If for any reason you shut off the printer while it is cleaning the nozzle, when it repowers, it instantly moves left hitting the cleaning lever and bending the screw that it is attached to. It also makes a loud noise when it does that. The easy fix would be to have it home to the -y axis first or whatever solution you guys decide to come up with. If I ever shut it off again in that scenario, I will now manually pull the head out of the cleaning area first. 

Reason I shut it down while doing the cleaning was that I realized that my model was sliced for the wrong filament.

**Comment by QIDITECH** [comment]
The lost step detection using the motor must leave enough space for the X and Y axes, so it is inevitable for the nozzle to retreat before printing.
But don't worry, in case of a collision, it won't damage any parts.
