### ISSUE TITLE
Spaces in gcode filename glitches

### ISSUE THREAD

**Issue by aidan-gibson** [QIDITECH/QIDI_Q1_Pro#95]
Using a usb, the printer will not load gcode if it has spaces in the filename.

Sending the file over LAN works but the printer screen shows an error.

Easy to work around of course but pretty annoying.

**Comment by whb0514** [comment]
Please send your file for review. Spaces should be fine unless your space is a special character. Or try to avoid naming with spaces as much as possible.

**Comment by aidan-gibson** [comment]
Here's an example that glitches wirelessly as well, presumably because `#` is prohibited too
[For Ikea Part # 101354_PLA_13m8s.txt](https://github.com/user-attachments/files/17435029/For.Ikea.Part.101354_PLA_13m8s.txt)
.

(I renamed extension to txt because github doesn't allow .gcode)

**Comment by aidan-gibson** [comment]
The console error is `!! Malformed command 'SDCARD_PRINT_FILE FILENAME=".cache/For Ikea Part # 101354_PLA_13m8s.gcode"'`

**Comment by whb0514** [comment]
Yes, some characters do go unrecognized, so try to avoid them.
